[package]
name = "evtx"
description = "A Fast (and safe) parser for the Windows XML Event Log (EVTX) format"
homepage = "https://github.com/omerbenamram/EVTX"
repository = "https://github.com/omerbenamram/EVTX"
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.1.1"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

exclude = [
    "**/*.evtx",
    "**/*.dat",
]

[dependencies]
crc = "1.8.1"
chrono = "0.4.6"
time = "0.1.42"
encoding = "0.2.33"
byteorder = "1.3.1"
xml-rs = "0.8.0"
env_logger = "0.6.0"
failure = "0.1.5"
log = { version = "^0.4", features=["release_max_level_debug"]}
clap = "2.32.0"
memmap = "0.7.0"
owning_ref = "0.4.0"
stable_deref_trait = "1.1.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.2"

[[bench]]
name = "benchmark"
path = "./src/benches/benchmark.rs"
harness = false
