[package]
name = "evtx"
description = "A Fast (and safe) parser for the Windows XML Event Log (EVTX) format"
homepage = "https://github.com/omerbenamram/EVTX"
repository = "https://github.com/omerbenamram/EVTX"
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.6.7-alpha.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

exclude = [
    "**/*.evtx",
    "**/*.dat",
]

[dependencies]
crc = "^1.8"
chrono = { version = "^0.4", features = ["serde"] }
encoding = "^0.2"
byteorder = "^1"
quick-xml = "^0.18"
thiserror = "1"
log = { version = "^0.4", features = ["release_max_level_debug"] }
winstructs = "0.3.0"
# Optional for multithreading.
rayon = { version = "1.3.0", optional = true }

# `evtx_dump` dependencies
anyhow = { version = "^1", optional = true}
simplelog = { version = "^0.7", optional = true }
clap = { version = "^2.33.0", optional = true }
dialoguer = { version = "^0.6.2", optional = true }
indoc = { version = "^0.3", optional = true }

serde = "^1.0"
serde_json = "^1.0"

[target.'cfg(not(windows))'.dependencies]
# jemalloc is significantly more peformant than the system allocator.
jemallocator = {version = "0.3.2", optional = true}

[target.'cfg(windows)'.dependencies]
# jemalloc is significantly more peformant than the system allocator.
rpmalloc = {version = "0.2.0", optional = true}


[features]
default = ["multithreading", "evtx_dump"]
fast-alloc = ["jemallocator", "rpmalloc"]
evtx_dump = ["simplelog", "clap", "dialoguer", "indoc", "anyhow", "fast-alloc"]
multithreading = ["rayon"]

[dev-dependencies]
pretty_assertions = "^0.6"
criterion = "^0.3"
skeptic = "0.13.4"
assert_cmd = "^1.0"
predicates = "^1"
env_logger = "^0.7"
tempfile = "^3.1"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"

# rexpect relies on unix process semantics, but it's only used for process interaction tests.
[target.'cfg(not(target_os = "windows"))'.dev-dependencies]
rexpect = "0.3.0"

[build-dependencies]
skeptic = "0.13.4"

[[bin]]
name = "evtx_dump"
required-features = ["evtx_dump"]

[[bench]]
name = "benchmark"
path = "./src/benches/benchmark.rs"
harness = false
