[package]
name = "evtx"
description = "A Fast (and safe) parser for the Windows XML Event Log (EVTX) format"
homepage = "https://github.com/omerbenamram/EVTX"
repository = "https://github.com/omerbenamram/EVTX"
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.6.3-alpha.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

exclude = [
    "**/*.evtx",
    "**/*.dat",
]

[dependencies]
crc = "1.8.1"
chrono = { version = "^0.4", features = ["serde"] }
encoding = "0.2.33"
byteorder = "1.3.2"
quick-xml = "0.17.0"
thiserror = "1"
log = { version = "^0.4", features = ["release_max_level_debug"] }
winstructs = "0.3.0"
# Optional for multithreading.
rayon = { version = "1.2.1", optional = true }

# `evtx_dump` dependencies
anyhow = { version = "1", optional = true}
simplelog = { version = "0.7.4", optional = true }
clap = { version = "2.33.0", optional = true }
dialoguer = { version = "0.5.0", optional = true }
indoc = { version = "0.3.4", optional = true }

serde = "^1.0"
serde_json = "^1.0"

[features]
default = ["multithreading", "evtx_dump"]
# Available only on nightly
backtraces = []
evtx_dump = ["simplelog", "clap", "dialoguer", "indoc", "anyhow"]
multithreading = ["rayon"]

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3.0"
skeptic = "0.13.4"
assert_cmd = "0.12.0"
predicates = "^1"
env_logger = "0.7.1"
tempfile = "3.1.0"

# rexpect relies on unix process semantics, but it's only used for process interaction tests.
[target.'cfg(not(target_os = "windows"))'.dev-dependencies]
rexpect = "0.3.0"

[build-dependencies]
skeptic = "0.13.4"

[[bin]]
name = "evtx_dump"
required-features = ["evtx_dump"]

[[bench]]
name = "benchmark"
path = "./src/benches/benchmark.rs"
harness = false
