[package]
name = "evtx"
description = "A Fast (and safe) parser for the Windows XML Event Log (EVTX) format"
homepage = "https://github.com/omerbenamram/EVTX"
repository = "https://github.com/omerbenamram/EVTX"
license = "MIT/Apache-2.0"
readme = "README.md"

version = "0.2.3-alpha.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

exclude = [
    "**/*.evtx",
    "**/*.dat",
]

[dependencies]
crc = "1.8.1"
chrono = {version = "0.4.6", features=["serde"]}
time = "0.1.42"
encoding = "0.2.33"
byteorder = "1.3.1"
quick-xml = "0.14.0"
env_logger = "0.6.1"
failure = "0.1.5"
log = { version = "^0.4", features=["release_max_level_debug"]}
clap = "2.33.0"
rayon = {version = "1.0.3", optional = true}

serde = { version = "1.0" }
serde_json = "1.0"

[features]
default = ["multithreading"]

multithreading = ["rayon"]

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.2"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"

[[bin]]
name = "evtx_dump"

[[bench]]
name = "benchmark"
path = "./src/benches/benchmark.rs"
harness = false
