[package]
name = "evtx-rs"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]

[dependencies]
hex-literal = "*"
crc = "^1.0.0"
chrono = "0.4"
time = "*"
encoding = "0.2.33"
byteorder = "1.2.3"
xml-rs = "*"
env_logger = "*"
failure = "*"
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_warn"] }

[dev-dependencies]
pretty_assertions = "*"
maplit = "*"
itertools = "*"