[package]
name = "evtx-rs"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]

[dependencies]
hex-literal = "*"
crc = "^1.0.0"
chrono = "0.4"
time = "*"
num-traits = "^0.2"
enum-primitive-derive = "^0.1"
encoding = "0.2.33"
env_logger = "*"
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_warn"] }
indextree = "*"
byteorder = "1.2.3"

[dependencies.nom]
version = "^4.0"
features = ["regexp", "verbose-errors"]

[dev-dependencies]
pretty_assertions = "*"

